[package]
name = "rust_example"
version = "0.1.0"
authors = ["Aaron Eidelson <aeidelson@dropbox.com>"]

[dependencies]
RPS = { path = "../../lib", version = "*"}
piston_window = "0.51.1"
uuid = { version = "0.3.0", features = [ "v4" ] }